### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [mghebre20/InstaParse#1]
It looks like your video walkthrough doesn't seem to show some of the required stories as follows:

1. User sees app icon in home screen.
2. User can sign up to create a new account using Parse authentication
3. The current signed in user is persisted across app restarts
4. User can pull to refresh the last 20 posts submitted to "Instagram"
5. User can tap a post to view post details, including timestamp and caption.

Can you update this and resubmit?

**Comment by codepathreview** [comment]
You can resubmit your video walkthrough with the stretch features until Monday 11:59 pm, Pacific Time. 
/cc @codepathreview

**Comment by mghebre20** [comment]
Hey, I've updated my readme with the walkthrough video but it seems the video is not showing on my end? It seems my file might be too big. Is there a url converter website I can use for my gif for resizing?

**Comment by mghebre20** [comment]
Hi,
I've managed to resolve the issue! Turns out I needed to create two gifs
since the file was too large.

**Comment by codepathreview** [comment]
Thank you for letting us know! 

We have revisited your submission and it seems like the GIF links in the repository encountered an error "non-image content-type returned". We have managed to review a working GIF and the following required stories are still missing:

1. The current signed in user is persisted across app restarts (to show this, the current login user's feeds should appear once you close the app and open it again)
2. User can pull to refresh the last 20 posts submitted to "Instagram" (doesn't need to have 20 posts but just shows a refresh in the feeds)
3. User can tap a post to view post details, including timestamp and caption (in the detail view the caption appeared however there is no timestamp)

Can you update this and resubmit? You can add another GIF showing these lacking required stories. 
/cc @codepathreview

**Comment by mghebre20** [comment]
Hi,
I included these in the second video all towards the end. You will see
these user stories after I demonstrated scrolling down to 20 posts part. It
starts with a pull to refresh and a lion post pops up!

**Comment by mghebre20** [comment]
Hey there,
I’m just following to see if you were able to see these user stories. The
video stops for a short period at the end and resumes demonstrating the
rest of the user stories?
